# -*- coding: utf-8 -*-
"""search_modify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_F92x2mAnHRaflbW8zvPT1pEq-QQXvV
"""

from google.colab import drive
drive.mount('/content/drive')

import csv
import pandas as pd
glinks=[]
with open('/content/drive/My Drive/Wiki/FINAL_wikidataAug25.csv', newline='') as csvfile:
  spamreader = csv.reader(csvfile, delimiter=',')
  for row in spamreader:
    glinks.append(row[18])
print(glinks)

f=[]
for i in glinks:
  if 'Google Result Number' in i:
    f.append(i)
    print(i)
  elif 'N/A' in i:
    f.append('N/A')
    print('N/A')
  elif '(' in i:
    j=i.index('(')-1
    k=i.replace(i[j:len(i)],'')
    k=k.replace('About ','')
    k=k.replace(' results','')
    f.append(k)
    print(k)
#print(f)

len(f)